### ISSUE TITLE
Where is the place to download the data?

### ISSUE THREAD

**Issue by sliawatimena** [nv-tlabs/STEAL#1]
```
(venv) (base) suryadi@xtal:/media/suryadi/DATA/learn/STEAL$ python inference_sbd.py \
>     --root_dir_val= ./data/sbd/data_aug/\
>     --flist_val= ./data/sbd/data_aug/val_list.txt\
>     --output_folder=./output/sbd/ \
>     --ckpt=./checkpoints/sbd/model_checkpoint.pt\
> 
usage: inference_sbd.py [-h] [--root_dir_val ROOT_DIR_VAL]
                        [--flist_val FLIST_VAL] [--ckpt CKPT]
                        [--output_folder OUTPUT_FOLDER] [--dataset DATASET]
                        [--n_classes N_CLASSES]
inference_sbd.py: error: unrecognized arguments: ./data/sbd/data_aug/ ./data/sbd/data_aug/val_list.txt

```

Dear David, 

Where to download data?
Is it correct from http://www.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/semantic_contours/benchmark.tgz ?

Thank you very much in advance.

Warmest Regards,
Suryadi

**Comment by davidjesusacu** [comment]
Yes, that path is correct.
For preprocessing, we follow CASENet. As stated in the readome, you can look here https://github.com/Chrisding/sbd-preprocess for the preprocessing scripts.

**Comment by woohoou** [comment]
The sbd directories changed, the readme use this commit:
https://github.com/Chrisding/sbd-preprocess/commit/21cc1f7339f6873487b53ca3e5b1286fe5d73775
