### ISSUE TITLE
Implementation of thinning layer

### ISSUE THREAD

**Issue by ourana35** [nv-tlabs/STEAL#5]
Hello, thank you for your excellent work. I've read your paper and i wonder whether you plan to release the code of training, especially the computation details of NMS loss and direction loss. Thank you.

**Comment by davidjesusacu** [comment]
Thanks! 
Unfortunately, we do not plan to release training code soon. 
However, implementing the thinning layer can be easily done by following this:
https://github.com/nv-tlabs/STEAL/blob/master/utils/edges_nms.m#L43-L54
