### ISSUE TITLE
how to get the result picture like this?

### ISSUE THREAD

**Issue by sunnyHelen** [nv-tlabs/STEAL#7]
when I use inference_cityscapes.py , it seems it will output different class into different images separately. I want to know how to get a total result like this in the paper?
![image](https://user-images.githubusercontent.com/28101548/63020177-bcbd8700-bee0-11e9-8683-73a556208f90.png)

**Comment by davidjesusacu** [comment]
You can assign a color code to the class predictions (individual images in each class_X folder) (we used the cityscapes palette) and paste them into a single image map. 
David
