### ISSUE TITLE
How to generate the ground truth normal direction

### ISSUE THREAD

**Issue by hsfzxjy** [nv-tlabs/STEAL#8]
Hi, thanks for your great work. I was curious about how the ground truth normal direction on boundaries is generated. It will be appreciated if you could share the implementation. Thank you.

**Comment by PkuRainBow** [comment]
+1

**Comment by davidjesusacu** [comment]
Hi, Thanks for the interest. 
You can have a look at how they are computed here: 
https://github.com/nv-tlabs/STEAL/blob/master/utils/edges_nms.m#L46-L50
Note that , as described in the readme, some of those functions require Piotr's Structured Forest matlab toolbox (https://github.com/pdollar/edges).
